# AdGuard Home Configuration - Optimized for Australian Deployment
# Security-hardened configuration with privacy-focused settings

http:
  pprof:
    port: 6060
    enabled: false
  address: 0.0.0.0:3000
  session_ttl: 720h

users:
  - name: admin
    password: $2a$10$example_hash_replace_this  # Replace with bcrypt hash

auth_attempts: 5
block_auth_min: 15

theme: auto
language: en

dns:
  bind_hosts:
    - 0.0.0.0
  port: 53

  # Australian-optimized upstream DNS servers
  upstream_dns:
    # Primary: Cloudflare Sydney PoP (fastest for Australia)
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query

    # Secondary: Quad9 (privacy-focused, Australia-friendly)
    - https://dns.quad9.net/dns-query
    - tls://dns.quad9.net

    # Tertiary: Google Sydney PoP (good performance backup)
    - https://dns.google/dns-query
    - 8.8.8.8

    # Emergency fallback (fast resolvers)
    - 9.9.9.9
    - 1.1.1.1

  upstream_dns_file: ""

  # Bootstrap DNS for DoH/DoT resolution
  bootstrap_dns:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 9.9.9.9

  # Fallback DNS for when all upstreams fail
  fallback_dns:
    - 1.1.1.1
    - 8.8.8.8

  upstream_mode: load_balance
  fastest_timeout: 1s
  allowed_clients: []
  disallowed_clients: []
  blocked_hosts:
    - version.bind
    - id.server
    - hostname.bind

  trusted_proxies:
    - 127.0.0.0/8
    - ::1/128

  cache_size: 4194304
  cache_ttl_min: 0
  cache_ttl_max: 0
  cache_optimistic: true

  bogus_nxdomain: []
  aaaa_disabled: false
  enable_dnssec: true
  edns_client_subnet:
    custom_ip: ""
    enabled: true
    use_custom: false

  max_goroutines: 300
  handle_ddr: true
  ipset: []
  ipset_file: ""

  # Rate limiting to prevent abuse
  ratelimit: 20
  ratelimit_whitelist: []

  # Refuse ANY queries (security measure)
  refuse_any: true

  # Serve plain DNS over port 53
  upstream_timeout: 10s
  private_networks:
    - 127.0.0.0/8
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
    - 169.254.0.0/16
    - ::1/128
    - fc00::/7
    - fe80::/10
    - fd00::/8

  use_private_ptr_resolvers: true
  local_ptr_upstreams:
    - 192.168.1.1  # Router for local PTR resolution

  # Serve stale cache entries when upstream is down
  serve_stale_for: 3600

  # DNS64 for IPv6 transition (disabled for home use)
  dns64_prefixes: []

  # Enable serving expired responses
  serve_http3: false
  use_http3_upstreams: false

  # Local domain resolution
  local_domain_name: "home.local"

tls:
  enabled: false
  server_name: ""
  force_https: false
  port_https: 443
  port_dns_over_tls: 853
  port_dns_over_quic: 853
  port_dnscrypt: 0
  dnscrypt_config_file: ""
  allow_unencrypted_doh: false
  certificate_chain: ""
  private_key: ""
  certificate_path: ""
  private_key_path: ""
  strict_sni_check: false

querylog:
  enabled: true
  file_enabled: true
  interval: 2160h  # 90 days
  size_memory: 1000
  ignored:
    - '|.^'

statistics:
  enabled: true
  interval: 24h
  ignored:
    - '|.^'

# Comprehensive filtering lists optimized for Australian users
filters:
  - enabled: true
    url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
    name: AdGuard DNS filter
    id: 1

  - enabled: true
    url: https://adaway.org/hosts.txt
    name: AdAway Default Blocklist
    id: 2

  - enabled: true
    url: https://v.firebog.net/hosts/AdguardDNS.txt
    name: Admiral - Anti-Adblock Bypass
    id: 3

  - enabled: true
    url: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareAdGuardHome.txt
    name: Dandelion Sprout's Anti-Malware List
    id: 4

  - enabled: true
    url: https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt
    name: DigitalSide Threat-Intel
    id: 5

  - enabled: true
    url: https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
    name: Disconnect.me Tracking Protection
    id: 6

  - enabled: true
    url: https://v.firebog.net/hosts/Easyprivacy.txt
    name: EasyPrivacy
    id: 7

  - enabled: true
    url: https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&showintro=1&mimetype=plaintext
    name: Peter Lowe's Ad and tracking server list
    id: 8

  - enabled: true
    url: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts
    name: UncheckyAds
    id: 9

  - enabled: true
    url: https://urlhaus.abuse.ch/downloads/hostfile/
    name: URLhaus Malware URL Blocklist
    id: 10

  - enabled: true
    url: https://v.firebog.net/hosts/Admiral.txt
    name: Admiral Anti-Adblock
    id: 11

  # Australian-specific privacy and security lists
  - enabled: true
    url: https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt
    name: Developer Dan's Ads & Tracking Extended
    id: 12

  - enabled: true
    url: https://someonewhocares.org/hosts/zero/hosts
    name: Dan Pollock's hosts file
    id: 13

  # Adult content filtering (comment out if not desired)
  - enabled: true
    url: https://raw.githubusercontent.com/StevenBlack/hosts/master/extensions/porn/hosts
    name: Steven Black's Adult Content Filter
    id: 14

  # Social media tracking
  - enabled: true
    url: https://www.github.developerdan.com/hosts/lists/facebook-extended.txt
    name: Facebook Extended
    id: 15

  # Cryptocurrency mining protection
  - enabled: true
    url: https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt
    name: NoCoin Filter List
    id: 16

whitelist_filters: []

user_rules:
  # Whitelist essential domains
  - '@@||gstatic.com^'
  - '@@||googleapis.com^'
  - '@@||googleusercontent.com^'
  - '@@||youtube.com^'
  - '@@||googlevideo.com^'
  - '@@||netflix.com^'
  - '@@||amazon.com^'
  - '@@||amazonaws.com^'
  - '@@||microsoft.com^'
  - '@@||apple.com^'
  - '@@||icloud.com^'
  - '@@||office.com^'

  # Australian-specific whitelists
  - '@@||com.au^'
  - '@@||gov.au^'
  - '@@||edu.au^'
  - '@@||mygovid.gov.au^'
  - '@@||centrelink.gov.au^'
  - '@@||ato.gov.au^'
  - '@@||bom.gov.au^'
  - '@@||abc.net.au^'
  - '@@||sbs.com.au^'
  - '@@||ninemsn.com.au^'
  - '@@||news.com.au^'
  - '@@||smh.com.au^'
  - '@@||theage.com.au^'
  - '@@||commbank.com.au^'
  - '@@||westpac.com.au^'
  - '@@||anz.com^'
  - '@@||nab.com.au^'
  - '@@||coles.com.au^'
  - '@@||woolworths.com.au^'
  - '@@||telstra.com.au^'
  - '@@||optus.com.au^'
  - '@@||vodafone.com.au^'
  - '@@||realestate.com.au^'
  - '@@||seek.com.au^'
  - '@@||gumtree.com.au^'

  # Block malicious domains
  - '||malware.example.com^'
  - '||phishing.example.com^'

  # Force SafeSearch on search engines
  - '|google.com^$dnsrewrite=NOERROR;CNAME;forcesafesearch.google.com'
  - '|www.google.com^$dnsrewrite=NOERROR;CNAME;forcesafesearch.google.com'
  - '|bing.com^$dnsrewrite=NOERROR;CNAME;strict.bing.com'
  - '|www.bing.com^$dnsrewrite=NOERROR;CNAME;strict.bing.com'
  - '|youtube.com^$dnsrewrite=NOERROR;CNAME;restrictmoderate.youtube.com'
  - '|www.youtube.com^$dnsrewrite=NOERROR;CNAME;restrictmoderate.youtube.com'

dhcp:
  enabled: false
  interface_name: ""
  local_domain_name: "home.local"
  dhcpv4:
    gateway_ip: ""
    subnet_mask: ""
    range_start: ""
    range_end: ""
    lease_duration: 86400
    icmp_timeout_msec: 1000
    options: []
  dhcpv6:
    range_start: ""
    lease_duration: 86400
    ra_slaac_only: false
    ra_allow_slaac: false

clients:
  runtime_sources:
    whois: true
    arp: true
    rdns: true
    dhcp: true
    hosts: true
  persistent: []

log_file: ""
log_max_backups: 0
log_max_size: 100
log_max_age: 3
log_compress: false
log_localtime: false
verbose: false
os:
  group: ""
  user: ""
  rlimit_nofile: 0
schema_version: 28
