# Prometheus configuration for AdGuard Home monitoring
# Optimized for home network monitoring with security focus

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s
  external_labels:
    cluster: 'adguard-home'
    environment: 'production'
    location: 'sydney-au'

rule_files:
  - "/etc/prometheus/rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
      timeout: 10s
      api_version: v2

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics
    honor_labels: true

  # AdGuard Home exporter
  - job_name: 'adguard-exporter'
    static_configs:
      - targets: ['adguard-exporter:9617']
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /metrics
    honor_labels: true
    params:
      format: ['prometheus']

  # System metrics via Node Exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /metrics
    honor_labels: true

  # AdGuard Home direct monitoring (if API is available)
  - job_name: 'adguard-home'
    static_configs:
      - targets: ['adguard:3000']
    scrape_interval: 60s
    scrape_timeout: 10s
    metrics_path: /control/stats
    honor_labels: true
    scheme: http

  # Docker daemon metrics (if enabled)
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /metrics
    honor_labels: true

  # Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 60s
    scrape_timeout: 10s
    metrics_path: /metrics
    honor_labels: true

  # Alertmanager metrics
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /metrics
    honor_labels: true

  # Blackbox exporter for external DNS testing
  - job_name: 'blackbox-dns'
    metrics_path: /probe
    params:
      module: [dns_tcp]
    static_configs:
      - targets:
        - 1.1.1.1:53      # Cloudflare
        - 8.8.8.8:53      # Google
        - 9.9.9.9:53      # Quad9
        - 192.168.1.1:53  # Router/Gateway
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Custom textfile collector metrics
  - job_name: 'textfile-collector'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 60s
    honor_labels: true
    metrics_path: /metrics
    params:
      collect[]: ['textfile']

# Storage configuration
storage:
  tsdb:
    path: /prometheus
    retention:
      time: 30d
      size: 10GB
    min-block-duration: 2h
    max-block-duration: 25h
    wal-compression: true

# Remote write configuration (for external monitoring services)
# remote_write:
#   - url: "https://prometheus.example.com/api/v1/write"
#     basic_auth:
#       username: "user"
#       password: "password"
#     write_relabel_configs:
#       - source_labels: [__name__]
#         regex: 'adguard_.*|node_.*'
#         action: keep

# Tracing configuration (if needed)
# tracing:
#   endpoint: "jaeger:14268/api/traces"
#   insecure: true